from themint.service.system_of_record_write_interface import SystemOfRecordWriteInterface
from themint.service.mint_message_service import MintMessageService

message_service = MintMessageService(SystemOfRecordWriteInterface())
